/**
 * Mapeamento de componentes disponíveis
 *
 * Este arquivo mapeia os nomes dos componentes para seus caminhos no repositório
 */

export interface ComponentInfo {
  name: string;
  type: "atom" | "molecule" | "organism";
  path: string;
  files: string[];
  dependencies?: string[];
}

/**
 * Mapeamento completo de todos os componentes disponíveis
 */
export const COMPONENT_MAP: Record<string, ComponentInfo> = {
  // Atoms
  button: {
    name: "button",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/button",
    files: ["button.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority", "cn"],
  },
  badge: {
    name: "badge",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/badge",
    files: ["badge.tsx", "index.ts"],
    dependencies: ["class-variance-authority", "cn"],
  },
  input: {
    name: "input",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/input",
    files: ["input.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-label", "cn"],
  },
  card: {
    name: "card",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/card",
    files: ["card.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  checkbox: {
    name: "checkbox",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/checkbox",
    files: ["checkbox.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-checkbox", "cn"],
  },
  skeleton: {
    name: "skeleton",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/skeleton",
    files: ["skeleton.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  table: {
    name: "table",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/table",
    files: ["table.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  tabs: {
    name: "tabs",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/tabs",
    files: ["tabs.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-tabs", "cn"],
  },
  alert: {
    name: "alert",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/alert",
    files: ["alert.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "alert-dialog": {
    name: "alert-dialog",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/alert-dialog",
    files: ["alert-dialog.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-alert-dialog", "cn"],
  },
  dialog: {
    name: "dialog",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/dialog",
    files: ["dialog.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-dialog", "cn"],
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/dropdown-menu",
    files: ["dropdown-menu.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-dropdown-menu", "cn"],
  },
  sonner: {
    name: "sonner",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/sonner",
    files: ["sonner.tsx", "index.ts"],
    dependencies: ["sonner", "lucide-react", "cn"],
  },
  tooltip: {
    name: "tooltip",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/tooltip",
    files: ["tooltip.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-tooltip", "cn"],
  },
  command: {
    name: "command",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/command",
    files: ["command.tsx", "index.ts"],
    dependencies: ["cmdk", "lucide-react", "cn"],
  },
  collapsible: {
    name: "collapsible",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/collapsible",
    files: ["collapsible.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-collapsible", "cn"],
  },
  "scroll-area": {
    name: "scroll-area",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/scroll-area",
    files: ["scroll-area.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-scroll-area", "cn"],
  },
  "hover-card": {
    name: "hover-card",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/hover-card",
    files: ["hover-card.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-hover-card", "cn"],
  },
  separator: {
    name: "separator",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/separator",
    files: ["separator.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-separator", "cn"],
  },
  loader: {
    name: "loader",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/loader",
    files: ["loader.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  shimmer: {
    name: "shimmer",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/shimmer",
    files: ["shimmer.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "undo-fuse-button": {
    name: "undo-fuse-button",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/undo-fuse-button",
    files: ["undo-fuse-button.tsx", "undo-fuse-button-utils.ts", "index.ts"],
    dependencies: ["motion", "lucide-react", "cn"],
  },
  "pull-send-button": {
    name: "pull-send-button",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/pull-send-button",
    files: ["pull-send-button.tsx", "pull-send-button-utils.ts", "index.ts"],
    dependencies: ["motion", "lucide-react", "cn"],
  },
  "slide-to-confirm": {
    name: "slide-to-confirm",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/slide-to-confirm",
    files: ["slide-to-confirm.tsx", "slide-to-confirm-utils.ts", "index.ts"],
    dependencies: ["motion", "lucide-react", "cn"],
  },
  "wave-bar-slider": {
    name: "wave-bar-slider",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/wave-bar-slider",
    files: ["wave-bar-slider.tsx", "wave-bar-slider-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-slider", "cn"],
  },
  "trail-dial": {
    name: "trail-dial",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/trail-dial",
    files: ["trail-dial.tsx", "trail-dial-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "scrub-number-field": {
    name: "scrub-number-field",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/scrub-number-field",
    files: ["scrub-number-field.tsx", "scrub-number-field-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "cascade-code-input": {
    name: "cascade-code-input",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/cascade-code-input",
    files: ["cascade-code-input.tsx", "cascade-code-input-utils.ts", "index.ts"],
    dependencies: ["motion", "input-otp", "cn"],
  },
  "glide-tooltip": {
    name: "glide-tooltip",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/glide-tooltip",
    files: ["glide-tooltip.tsx", "glide-tooltip-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "hold-button": {
    name: "hold-button",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/hold-button",
    files: ["hold-button.tsx", "hold-button-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "stretch-switch": {
    name: "stretch-switch",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/stretch-switch",
    files: ["stretch-switch.tsx", "stretch-switch-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-switch", "cn"],
  },
  "strike-checkbox": {
    name: "strike-checkbox",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/strike-checkbox",
    files: ["strike-checkbox.tsx", "strike-checkbox-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-checkbox", "cn"],
  },
  "swell-chip-group": {
    name: "swell-chip-group",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/swell-chip-group",
    files: ["swell-chip-group.tsx", "swell-chip-group-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-radio-group", "cn"],
  },
  "lift-rating": {
    name: "lift-rating",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/lift-rating",
    files: ["lift-rating.tsx", "lift-rating-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-radio-group", "lucide-react", "cn"],
  },
  "elastic-segment": {
    name: "elastic-segment",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/elastic-segment",
    files: ["elastic-segment.tsx", "elastic-segment-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-radio-group", "cn"],
  },
  "notify-toggle": {
    name: "notify-toggle",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/notify-toggle",
    files: ["notify-toggle.tsx", "notify-toggle-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-toggle", "lucide-react", "cn"],
  },
  "like-button": {
    name: "like-button",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/like-button",
    files: ["like-button.tsx", "like-button-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-toggle", "lucide-react", "cn"],
  },
  "glide-picker": {
    name: "glide-picker",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/glide-picker",
    files: ["glide-picker.tsx", "glide-picker-utils.ts", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-dropdown-menu", "lucide-react", "cn"],
  },
  "curved-loop": {
    name: "curved-loop",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/curved-loop",
    files: ["curved-loop.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "cursor-trail": {
    name: "cursor-trail",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/cursor-trail",
    files: ["cursor-trail.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "scroll-velocity": {
    name: "scroll-velocity",
    type: "molecule",
    path: "packages/ui/src/components/molecules/animation/scroll-velocity",
    files: ["scroll-velocity.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "fuzzy-text": {
    name: "fuzzy-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/fuzzy-text",
    files: ["fuzzy-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "particle-text": {
    name: "particle-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/particle-text",
    files: ["particle-text.tsx", "particle-text-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "tech-text": {
    name: "tech-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/tech-text",
    files: ["tech-text.tsx", "tech-text-utils.ts", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "blur-text": {
    name: "blur-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/blur-text",
    files: ["blur-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "glitch-text": {
    name: "glitch-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/glitch-text",
    files: ["glitch-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "true-focus": {
    name: "true-focus",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/true-focus",
    files: ["true-focus.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "split-flap-text": {
    name: "split-flap-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/split-flap-text",
    files: ["split-flap-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "variable-proximity": {
    name: "variable-proximity",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/variable-proximity",
    files: ["variable-proximity.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "text-pressure": {
    name: "text-pressure",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/text-pressure",
    files: ["text-pressure.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "depth-text": {
    name: "depth-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/depth-text",
    files: ["depth-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "echo-text": {
    name: "echo-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/echo-text",
    files: ["echo-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "count-up": {
    name: "count-up",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/count-up",
    files: ["count-up.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "gradient-text": {
    name: "gradient-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/gradient-text",
    files: ["gradient-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "rotating-text": {
    name: "rotating-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/rotating-text",
    files: ["rotating-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "circular-text": {
    name: "circular-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/typography/circular-text",
    files: ["circular-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "code-block": {
    name: "code-block",
    type: "atom",
    path: "packages/ui/src/components/atoms/code/code-block",
    files: ["code-block.tsx", "index.ts"],
    dependencies: ["shiki", "lucide-react", "cn"],
  },
  snippet: {
    name: "snippet",
    type: "atom",
    path: "packages/ui/src/components/atoms/code/snippet",
    files: ["snippet.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "inline-citation": {
    name: "inline-citation",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/inline-citation",
    files: ["inline-citation.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  label: {
    name: "label",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/label",
    files: ["label.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-label", "cn"],
  },
  "radio-group": {
    name: "radio-group",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/radio-group",
    files: ["radio-group.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-radio-group", "lucide-react", "cn"],
  },
  switch: {
    name: "switch",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/switch",
    files: ["switch.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-switch", "cn"],
  },
  textarea: {
    name: "textarea",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/textarea",
    files: ["textarea.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "date-input": {
    name: "date-input",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/date-input",
    files: ["date-input.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "time-input": {
    name: "time-input",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/time-input",
    files: ["time-input.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  slider: {
    name: "slider",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/slider",
    files: ["slider.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-slider", "cn"],
  },
  toggle: {
    name: "toggle",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/toggle",
    files: ["toggle.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-toggle", "class-variance-authority", "cn"],
  },
  popover: {
    name: "popover",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/popover",
    files: ["popover.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-popover", "cn"],
  },
  sheet: {
    name: "sheet",
    type: "atom",
    path: "packages/ui/src/components/atoms/feedback/sheet",
    files: ["sheet.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-dialog", "lucide-react", "cn"],
  },
  breadcrumb: {
    name: "breadcrumb",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/breadcrumb",
    files: ["breadcrumb.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-slot", "lucide-react", "cn"],
  },
  pagination: {
    name: "pagination",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/pagination",
    files: ["pagination.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  spinner: {
    name: "spinner",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/spinner",
    files: ["spinner.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "encrypted-text": {
    name: "encrypted-text",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/encrypted-text",
    files: ["encrypted-text.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  accordion: {
    name: "accordion",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/accordion",
    files: ["accordion.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-accordion", "lucide-react", "cn"],
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/aspect-ratio",
    files: ["aspect-ratio.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-aspect-ratio"],
  },
  "toggle-group": {
    name: "toggle-group",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/toggle-group",
    files: ["toggle-group.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-toggle-group", "class-variance-authority", "cn"],
  },
  drawer: {
    name: "drawer",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/drawer",
    files: ["drawer.tsx", "index.ts"],
    dependencies: ["vaul", "cn"],
  },
  sidebar: {
    name: "sidebar",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/sidebar",
    files: ["sidebar.tsx", "index.ts"],
    dependencies: [
      "@radix-ui/react-slot",
      "class-variance-authority",
      "lucide-react",
      "@flowtomic/logic",
      "cn",
    ],
  },
  empty: {
    name: "empty",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/empty",
    files: ["empty.tsx", "index.ts"],
    dependencies: ["class-variance-authority", "cn"],
  },
  kbd: {
    name: "kbd",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/kbd",
    files: ["kbd.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "context-menu": {
    name: "context-menu",
    type: "atom",
    path: "packages/ui/src/components/atoms/actions/context-menu",
    files: ["context-menu.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-context-menu", "lucide-react", "cn"],
  },
  field: {
    name: "field",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/field",
    files: ["field.tsx", "index.ts"],
    dependencies: ["class-variance-authority", "lucide-react", "cn"],
  },
  form: {
    name: "form",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/form",
    files: ["form.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-label", "@radix-ui/react-slot", "react-hook-form", "cn"],
  },
  "input-otp": {
    name: "input-otp",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/input-otp",
    files: ["input-otp.tsx", "index.ts"],
    dependencies: ["input-otp", "lucide-react", "cn"],
  },
  menubar: {
    name: "menubar",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/menubar",
    files: ["menubar.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-menubar", "lucide-react", "cn"],
  },
  "navigation-menu": {
    name: "navigation-menu",
    type: "atom",
    path: "packages/ui/src/components/atoms/navigation/navigation-menu",
    files: ["navigation-menu.tsx", "index.ts"],
    dependencies: [
      "@radix-ui/react-navigation-menu",
      "class-variance-authority",
      "lucide-react",
      "cn",
    ],
  },
  calendar: {
    name: "calendar",
    type: "atom",
    path: "packages/ui/src/components/atoms/data-display/calendar",
    files: ["calendar.tsx", "index.ts"],
    dependencies: ["react-day-picker", "lucide-react", "cn"],
  },
  carousel: {
    name: "carousel",
    type: "atom",
    path: "packages/ui/src/components/atoms/data-display/carousel",
    files: ["carousel.tsx", "index.ts"],
    dependencies: ["embla-carousel-react", "lucide-react", "cn"],
  },
  chart: {
    name: "chart",
    type: "atom",
    path: "packages/ui/src/components/atoms/data-display/chart",
    files: ["chart.tsx", "index.ts"],
    dependencies: ["recharts", "cn"],
  },
  "qr-code": {
    name: "qr-code",
    type: "atom",
    path: "packages/ui/src/components/atoms/data-display/qr-code",
    files: ["qr-code.tsx", "index.ts"],
    dependencies: ["qr-code-styling", "class-variance-authority", "cn"],
  },
  select: {
    name: "select",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/select",
    files: ["select.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-select", "lucide-react", "cn"],
  },
  "native-select": {
    name: "native-select",
    type: "atom",
    path: "packages/ui/src/components/atoms/forms/native-select",
    files: ["native-select.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  avatar: {
    name: "avatar",
    type: "atom",
    path: "packages/ui/src/components/atoms/display/avatar",
    files: ["avatar.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "backdrop-blur": {
    name: "backdrop-blur",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/backdrop-blur",
    files: ["backdrop-blur.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  progress: {
    name: "progress",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/progress",
    files: ["progress.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "animated-3d": {
    name: "animated-3d",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/animated-3d",
    files: ["animated-3d.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "sliding-number": {
    name: "sliding-number",
    type: "atom",
    path: "packages/ui/src/components/atoms/animation/sliding-number",
    files: ["sliding-number.tsx", "index.ts"],
    dependencies: ["motion", "react-use-measure", "cn"],
  },
  resizable: {
    name: "resizable",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/resizable",
    files: ["resizable.tsx", "index.ts"],
    dependencies: ["react-resizable-panels", "lucide-react", "cn"],
  },

  // Molecules
  "button-group": {
    name: "button-group",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/button-group",
    files: ["button-group.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "password-input": {
    name: "password-input",
    type: "molecule",
    path: "packages/ui/src/components/molecules/auth/password-input",
    files: ["password-input.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "image-dropzone": {
    name: "image-dropzone",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/image-dropzone",
    files: ["image-dropzone.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "stat-card": {
    name: "stat-card",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/stat-card",
    files: ["stat-card.tsx", "index.ts"],
    dependencies: ["flowtomic/logic", "lucide-react", "cn"],
  },
  "data-table": {
    name: "data-table",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/data-table",
    files: ["data-table.tsx", "index.ts"],
    dependencies: ["@tanstack/react-table", "lucide-react", "cn"],
  },
  "menu-dock": {
    name: "menu-dock",
    type: "molecule",
    path: "packages/ui/src/components/molecules/navigation/menu-dock",
    files: ["menu-dock.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "theme-toggle-button": {
    name: "theme-toggle-button",
    type: "molecule",
    path: "packages/ui/src/components/molecules/theme/theme-toggle-button",
    files: ["theme-toggle-button.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "auth-navigation-link": {
    name: "auth-navigation-link",
    type: "molecule",
    path: "packages/ui/src/components/molecules/auth/auth-navigation-link",
    files: ["auth-navigation-link.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "auth-form-error-message": {
    name: "auth-form-error-message",
    type: "molecule",
    path: "packages/ui/src/components/molecules/auth/auth-form-error-message",
    files: ["auth-form-error-message.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "social-login-buttons": {
    name: "social-login-buttons",
    type: "molecule",
    path: "packages/ui/src/components/molecules/auth/social-login-buttons",
    files: ["social-login-buttons.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "input-group": {
    name: "input-group",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/input-group",
    files: ["input-group.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "calendar-popover": {
    name: "calendar-popover",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/calendar-popover",
    files: ["calendar-popover.tsx", "index.ts"],
    dependencies: ["date-fns", "lucide-react", "cn"],
  },
  "calendar-range": {
    name: "calendar-range",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/calendar-range",
    files: ["calendar-range.tsx", "index.ts"],
    dependencies: ["date-fns", "react-day-picker", "lucide-react", "cn"],
  },
  "numeric-filter-field": {
    name: "numeric-filter-field",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/numeric-filter-field",
    files: ["numeric-filter-field.tsx", "index.ts"],
    dependencies: ["react-number-format", "cn"],
  },
  "inline-datetime-editor": {
    name: "inline-datetime-editor",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/inline-datetime-editor",
    files: ["inline-datetime-editor.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  combobox: {
    name: "combobox",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/combobox",
    files: ["combobox.tsx", "index.ts"],
    dependencies: ["@base-ui/react", "lucide-react", "cn"],
  },
  autocomplete: {
    name: "autocomplete",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/autocomplete",
    files: [
      "autocomplete.tsx",
      "autocomplete-item.tsx",
      "autocomplete-section.tsx",
      "autocomplete-context.tsx",
      "index.ts",
    ],
    dependencies: ["@radix-ui/react-popover", "flowtomic/logic", "lucide-react", "cn"],
  },
  artifact: {
    name: "artifact",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/artifact",
    files: ["artifact.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  message: {
    name: "message",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/message",
    files: ["message.tsx", "index.ts"],
    dependencies: ["streamdown", "lucide-react", "cn", "ai"],
  },
  suggestion: {
    name: "suggestion",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/suggestion",
    files: ["suggestion.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  sources: {
    name: "sources",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/sources",
    files: ["sources.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  tool: {
    name: "tool",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/tool",
    files: ["tool.tsx", "index.ts"],
    dependencies: ["ai", "lucide-react", "cn"],
  },
  "tool-status-line": {
    name: "tool-status-line",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/tool-status-line",
    files: ["tool-status-line.tsx", "index.ts"],
    dependencies: ["lucide-react", "motion", "cn"],
  },
  task: {
    name: "task",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/task",
    files: ["task.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  checkpoint: {
    name: "checkpoint",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/checkpoint",
    files: ["checkpoint.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  confirmation: {
    name: "confirmation",
    type: "molecule",
    path: "packages/ui/src/components/molecules/feedback/confirmation",
    files: ["confirmation.tsx", "index.ts"],
    dependencies: ["ai", "cn"],
  },
  "chart-area-interactive": {
    name: "chart-area-interactive",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/chart-area-interactive",
    files: ["chart-area-interactive.tsx", "index.ts"],
    dependencies: ["recharts", "cn"],
  },
  "chart-bar-interactive": {
    name: "chart-bar-interactive",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/chart-bar-interactive",
    files: ["chart-bar-interactive.tsx", "index.ts"],
    dependencies: ["recharts", "cn"],
  },
  item: {
    name: "item",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/item",
    files: ["item.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority", "cn"],
  },
  "sidebar-navigation": {
    name: "sidebar-navigation",
    type: "molecule",
    path: "packages/ui/src/components/molecules/navigation/sidebar-navigation",
    files: ["sidebar-navigation.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "bar-chart": {
    name: "bar-chart",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/bar-chart",
    files: ["bar-chart.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  bubble: {
    name: "bubble",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/bubble",
    files: ["bubble.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority", "cn"],
  },
  "time-tracker": {
    name: "time-tracker",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/time-tracker",
    files: ["time-tracker.tsx", "index.ts"],
    dependencies: ["@flowtomic/logic", "lucide-react", "cn"],
  },
  "team-member-list": {
    name: "team-member-list",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/team-member-list",
    files: ["team-member-list.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "reminder-card": {
    name: "reminder-card",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/reminder-card",
    files: ["reminder-card.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "circular-progress-chart": {
    name: "circular-progress-chart",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/circular-progress-chart",
    files: ["circular-progress-chart.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "project-list": {
    name: "project-list",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/project-list",
    files: ["project-list.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "text-editor": {
    name: "text-editor",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/text-editor",
    files: ["text-editor.tsx", "index.ts"],
    dependencies: [
      "@tiptap/react",
      "@tiptap/starter-kit",
      "@tiptap/extension-color",
      "@tiptap/extension-image",
      "@tiptap/extension-placeholder",
      "@tiptap/extension-text-align",
      "@tiptap/extension-text-style",
      "tiptap-markdown",
      "streamdown",
      "lucide-react",
      "cn",
    ],
  },
  "button-counter": {
    name: "button-counter",
    type: "molecule",
    path: "packages/ui/src/components/molecules/animation/button-counter",
    files: ["button-counter.tsx", "index.ts"],
    dependencies: ["motion", "cn"],
  },
  "animated-sliding-number": {
    name: "animated-sliding-number",
    type: "molecule",
    path: "packages/ui/src/components/molecules/animation/animated-sliding-number",
    files: ["animated-sliding-number.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "animated-modal": {
    name: "animated-modal",
    type: "molecule",
    path: "packages/ui/src/components/molecules/animation/animated-modal",
    files: ["animated-modal.tsx", "index.ts"],
    dependencies: ["motion", "@radix-ui/react-dialog", "lucide-react", "cn"],
  },
  "dashboard-header": {
    name: "dashboard-header",
    type: "molecule",
    path: "packages/ui/src/components/molecules/layout/dashboard-header",
    files: ["dashboard-header.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },

  // Organisms
  "dashboard-layout": {
    name: "dashboard-layout",
    type: "organism",
    path: "packages/ui/src/components/organisms/dashboard-layout",
    files: ["dashboard-layout.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "stats-grid": {
    name: "stats-grid",
    type: "organism",
    path: "packages/ui/src/components/organisms/stats-grid",
    files: ["stats-grid.tsx", "index.ts"],
    dependencies: ["cn"],
  },
  "monthly-summary": {
    name: "monthly-summary",
    type: "organism",
    path: "packages/ui/src/components/organisms/monthly-summary",
    files: ["monthly-summary.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "dashboard-header-actions": {
    name: "dashboard-header-actions",
    type: "organism",
    path: "packages/ui/src/components/organisms/dashboard-header-actions",
    files: ["dashboard-header-actions.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "dashboard-movements-section": {
    name: "dashboard-movements-section",
    type: "organism",
    path: "packages/ui/src/components/organisms/dashboard-movements-section",
    files: ["dashboard-movements-section.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  conversation: {
    name: "conversation",
    type: "organism",
    path: "packages/ui/src/components/organisms/conversation",
    files: ["conversation.tsx", "index.ts"],
    dependencies: ["use-stick-to-bottom", "lucide-react", "cn"],
  },
  "model-selector": {
    name: "model-selector",
    type: "organism",
    path: "packages/ui/src/components/organisms/model-selector",
    files: ["model-selector.tsx", "index.ts"],
    dependencies: ["cmdk", "cn"],
  },
  image: {
    name: "image",
    type: "organism",
    path: "packages/ui/src/components/organisms/image",
    files: ["image.tsx", "index.ts"],
    dependencies: ["ai", "cn"],
  },
  "open-in-chat": {
    name: "open-in-chat",
    type: "organism",
    path: "packages/ui/src/components/organisms/open-in-chat",
    files: ["open-in-chat.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  panel: {
    name: "panel",
    type: "organism",
    path: "packages/ui/src/components/organisms/panel",
    files: ["panel.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  toolbar: {
    name: "toolbar",
    type: "organism",
    path: "packages/ui/src/components/organisms/toolbar",
    files: ["toolbar.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  controls: {
    name: "controls",
    type: "organism",
    path: "packages/ui/src/components/organisms/controls",
    files: ["controls.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  connection: {
    name: "connection",
    type: "molecule",
    path: "packages/ui/src/components/molecules/flow/connection",
    files: ["connection.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  queue: {
    name: "queue",
    type: "organism",
    path: "packages/ui/src/components/organisms/queue",
    files: ["queue.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  reasoning: {
    name: "reasoning",
    type: "organism",
    path: "packages/ui/src/components/organisms/reasoning",
    files: ["reasoning.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-use-controllable-state", "streamdown", "lucide-react", "cn"],
  },
  plan: {
    name: "plan",
    type: "organism",
    path: "packages/ui/src/components/organisms/plan",
    files: ["plan.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "web-preview": {
    name: "web-preview",
    type: "organism",
    path: "packages/ui/src/components/organisms/web-preview",
    files: ["web-preview.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "script-editor": {
    name: "script-editor",
    type: "organism",
    path: "packages/ui/src/components/organisms/script-editor",
    files: ["script-editor.tsx", "index.ts"],
    dependencies: ["@flowtomic/logic", "lucide-react", "cn"],
  },
  "chain-of-thought": {
    name: "chain-of-thought",
    type: "organism",
    path: "packages/ui/src/components/organisms/chain-of-thought",
    files: ["chain-of-thought.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-use-controllable-state", "lucide-react", "cn"],
  },
  context: {
    name: "context",
    type: "organism",
    path: "packages/ui/src/components/organisms/context",
    files: ["context.tsx", "index.ts"],
    dependencies: ["tokenlens", "ai", "lucide-react", "cn"],
  },
  "prompt-input": {
    name: "prompt-input",
    type: "organism",
    path: "packages/ui/src/components/organisms/prompt-input",
    files: ["prompt-input.tsx", "index.ts"],
    dependencies: ["ai", "nanoid", "lucide-react", "cmdk", "cn"],
  },
  questionnaire: {
    name: "questionnaire",
    type: "organism",
    path: "packages/ui/src/components/organisms/questionnaire",
    files: ["questionnaire.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-radio-group", "lucide-react", "motion", "cn"],
  },
  canvas: {
    name: "canvas",
    type: "molecule",
    path: "packages/ui/src/components/molecules/flow/canvas",
    files: ["canvas.tsx", "index.ts"],
    dependencies: ["@xyflow/react"],
  },
  node: {
    name: "node",
    type: "organism",
    path: "packages/ui/src/components/organisms/node",
    files: ["node.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  edge: {
    name: "edge",
    type: "organism",
    path: "packages/ui/src/components/organisms/edge",
    files: ["edge.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "cn"],
  },
  "resizable-layout": {
    name: "resizable-layout",
    type: "organism",
    path: "packages/ui/src/components/organisms/resizable-layout",
    files: ["resizable-layout.tsx", "index.ts"],
    dependencies: ["@flowtomic/logic", "react-resizable-panels", "lucide-react", "cn"],
  },
  "widget-resize-handle": {
    name: "widget-resize-handle",
    type: "atom",
    path: "packages/ui/src/components/atoms/layout/widget-resize-handle",
    files: ["widget-resize-handle.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "edit-mode-toggle": {
    name: "edit-mode-toggle",
    type: "molecule",
    path: "packages/ui/src/components/molecules/edit-mode-toggle",
    files: ["edit-mode-toggle.tsx", "index.ts"],
    dependencies: ["lucide-react", "@flowtomic/ui", "cn"],
  },
  "draggable-widget": {
    name: "draggable-widget",
    type: "molecule",
    path: "packages/ui/src/components/molecules/draggable-widget",
    files: ["draggable-widget.tsx", "index.ts"],
    dependencies: ["@dnd-kit/core", "@dnd-kit/utilities", "lucide-react", "@flowtomic/ui", "cn"],
  },
  "widget-renderer": {
    name: "widget-renderer",
    type: "molecule",
    path: "packages/ui/src/components/molecules/widget-renderer",
    files: ["widget-renderer.tsx", "index.ts"],
    dependencies: ["@flowtomic/ui", "cn"],
  },
  "draggable-dashboard-grid": {
    name: "draggable-dashboard-grid",
    type: "organism",
    path: "packages/ui/src/components/organisms/draggable-dashboard-grid",
    files: ["draggable-dashboard-grid.tsx", "index.ts"],
    dependencies: [
      "@dnd-kit/core",
      "@dnd-kit/utilities",
      "@flowtomic/logic",
      "@flowtomic/ui",
      "cn",
    ],
  },
  "widget-palette": {
    name: "widget-palette",
    type: "organism",
    path: "packages/ui/src/components/organisms/widget-palette",
    files: ["widget-palette.tsx", "index.ts"],
    dependencies: ["@dnd-kit/core", "lucide-react", "cn"],
  },
  "widget-config-modal": {
    name: "widget-config-modal",
    type: "organism",
    path: "packages/ui/src/components/organisms/widget-config-modal",
    files: ["widget-config-modal.tsx", "index.ts"],
    dependencies: ["@flowtomic/ui", "react-hook-form", "zod", "cn"],
  },
  "chat-message": {
    name: "chat-message",
    type: "molecule",
    path: "packages/ui/src/components/molecules/data-display/chat-message",
    files: ["chat-message.tsx", "index.ts"],
    dependencies: ["react-markdown", "lucide-react", "@radix-ui/react-dropdown-menu", "cn"],
  },
  "chat-log": {
    name: "chat-log",
    type: "organism",
    path: "packages/ui/src/components/organisms/chat-log",
    files: ["chat-log.tsx", "index.ts"],
    dependencies: ["use-stick-to-bottom", "lucide-react", "cn"],
  },
  "chat-input": {
    name: "chat-input",
    type: "molecule",
    path: "packages/ui/src/components/molecules/forms/chat-input",
    files: ["chat-input.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "edit-chat-message-modal": {
    name: "edit-chat-message-modal",
    type: "molecule",
    path: "packages/ui/src/components/molecules/feedback/edit-chat-message-modal",
    files: ["edit-chat-message-modal.tsx", "index.ts"],
    dependencies: ["@radix-ui/react-dialog", "lucide-react", "cn"],
  },
  "document-editor": {
    name: "document-editor",
    type: "organism",
    path: "packages/ui/src/components/organisms/document-editor",
    files: ["document-editor.tsx", "index.ts"],
    dependencies: ["lucide-react", "cn"],
  },
  "form-layout": {
    name: "form-layout",
    type: "organism",
    path: "packages/ui/src/components/organisms/form-layout",
    files: ["form-layout.tsx", "index.ts"],
    dependencies: ["react-hook-form", "react-number-format", "cn"],
  },
  "genealogy-canvas": {
    name: "genealogy-canvas",
    type: "organism",
    path: "packages/ui/src/components/organisms/genealogy-canvas",
    files: ["genealogy-canvas.tsx", "index.ts"],
    dependencies: ["@xyflow/react", "@flowtomic/logic", "cn"],
  },
};

/**
 * Mapeamento de hooks disponíveis
 */
export const HOOK_MAP: Record<string, ComponentInfo> = {
  "use-stat-card": {
    name: "useStatCard",
    type: "atom",
    path: "packages/logic/src/hooks/useStatCard",
    files: ["useStatCard.ts"],
    dependencies: ["react"],
  },
  "use-dashboard-layout": {
    name: "useDashboardLayout",
    type: "atom",
    path: "packages/logic/src/hooks/useDashboardLayout",
    files: ["useDashboardLayout.ts", "index.ts"],
    dependencies: ["react"],
  },
};

/**
 * Busca um componente ou hook pelo nome
 */
export function findComponent(name: string): ComponentInfo | null {
  // Normalizar nome
  const normalized = name.toLowerCase().replace(/\s+/g, "-");

  // Buscar em componentes
  if (COMPONENT_MAP[normalized]) {
    return COMPONENT_MAP[normalized];
  }

  // Buscar em hooks
  if (HOOK_MAP[normalized]) {
    return HOOK_MAP[normalized];
  }

  // Tentar busca por alias comum
  const aliases: Record<string, string> = {
    btn: "button",
    "input-field": "input",
    stat: "stat-card",
    table: "data-table",
    menu: "menu-dock",
    "theme-toggle": "theme-toggle-button",
    layout: "dashboard-layout",
    grid: "stats-grid",
    summary: "monthly-summary",
    "header-actions": "dashboard-header-actions",
    movements: "dashboard-movements-section",
    "edit-toggle": "edit-mode-toggle",
    "widget-resize": "widget-resize-handle",
    "dashboard-grid": "draggable-dashboard-grid",
    palette: "widget-palette",
    "config-modal": "widget-config-modal",
  };

  if (aliases[normalized]) {
    return COMPONENT_MAP[aliases[normalized]] || HOOK_MAP[aliases[normalized]] || null;
  }

  return null;
}

/**
 * Lista todos os componentes disponíveis
 */
export function listComponents(): ComponentInfo[] {
  return Object.values(COMPONENT_MAP);
}

/**
 * Lista todos os hooks disponíveis
 */
export function listHooks(): ComponentInfo[] {
  return Object.values(HOOK_MAP);
}
